export default [
    // SCREEN 1
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 188,
            top: 10,
            left: 17,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 150,
            top: 55,
            left: 32,
            zIndex: 2,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 160,
            top: 10,
            left: 65,
            zIndex: 0,
        },
        {
            startIndex: 450,
            numImages: 150,
            duration: 3,
            size: 100,
            top: 30,
            left: 50,
            zIndex: 0,
        },
        {
            startIndex: 600,
            numImages: 150,
            duration: 3,
            size: 250,
            top: 35,
            left: 70,
            zIndex: 0,
        },
        {
            startIndex: 750,
            numImages: 150,
            duration: 3,
            size: 150,
            top: 20,
            left: 0,
            zIndex: 0,
        },
        {
            startIndex: 900,
            numImages: 150,
            duration: 3,
            size: 158,
            top: 60,
            left: 5,
            zIndex: 0,
        },
    ],

    // SCREEN 2
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 162,
            top: 22,
            left: 11,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 122,
            top: 2,
            left: 64,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 130,
            top: 58,
            left: 46,
            zIndex: 0,
        },
        {
            startIndex: 450,
            numImages: 150,
            duration: 3,
            size: 150,
            top: 62,
            left: 11,
            zIndex: 0,
        },
        {
            startIndex: 600,
            numImages: 150,
            duration: 3,
            size: 98,
            top: 32,
            left: 84,
            zIndex: 2,
        },
        {
            startIndex: 750,
            numImages: 150,
            duration: 3,
            size: 197,
            top: 20,
            left: 56,
            zIndex: 0,
        },
    ],

    // SCREEN 3
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 248,
            top: 0,
            left: 3,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 101,
            top: 21,
            left: 47,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 116,
            top: 40,
            left: 69,
            zIndex: 0,
        },
        {
            startIndex: 450,
            numImages: 150,
            duration: 3,
            size: 100,
            top: 50,
            left: 35,
            zIndex: 2,
        },
        {   
            startIndex: 750,
            numImages: 150,
            duration: 3,
            size: 197,
            top: 0,
            left: 75,
            zIndex: 0,
        }
    ],

]